### ISSUE TITLE
Error on emales example

### ISSUE THREAD

**Issue by thackl** [GijsBakker/VVODKA#49]
I'm trying to run VVODKA on the emales example, but run into the following error:

```
(base) [thackl@Yaxha:..ode/projects/VVODKA/PythonCode/Scripts                                                                      main 13:16:43]
python3 ./VVODKA.py -k15 ../../data/emales/emale04.fna
Extracting Sequences
Matching BVI_055B against BVI_055B
Finding overlapping sequences
Matching BVI_055B against BVI_002
Finding overlapping sequences
Matching BVI_055B against BVI_096B
Finding overlapping sequences
Matching BVI_002 against BVI_002
Finding overlapping sequences
Matching BVI_002 against BVI_096B
Finding overlapping sequences
Matching BVI_096B against BVI_096B
Finding overlapping sequences
Making plots
Traceback (most recent call last):
  File "/home/thackl/Code/projects/VVODKA/PythonCode/Scripts/./VVODKA.py", line 135, in <module>
    main(args)
  File "/home/thackl/Code/projects/VVODKA/PythonCode/Scripts/./VVODKA.py", line 126, in main
    vvodka(kmer_size, files, on_self, dpi, dot_size)
  File "/home/thackl/Code/projects/VVODKA/PythonCode/Scripts/./VVODKA.py", line 115, in vvodka
    fig.savefig(file, dpi=dpi)
  File "/home/thackl/mambaforge/lib/python3.9/site-packages/matplotlib/figure.py", line 3328, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/home/thackl/mambaforge/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2362, in print_figure
    result = print_method(
  File "/home/thackl/mambaforge/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2228, in <lambda>
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/home/thackl/mambaforge/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 509, in print_png
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/home/thackl/mambaforge/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 458, in _print_pil
    mpl.image.imsave(
  File "/home/thackl/mambaforge/lib/python3.9/site-packages/matplotlib/image.py", line 1687, in imsave
    image.save(fname, **pil_kwargs)
  File "/home/thackl/mambaforge/lib/python3.9/site-packages/PIL/Image.py", line 2410, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '../Results/BVI_055B_on_self.png'
```

**Comment by GijsBakker** [comment]
A Results folder has been added, so this issue should be fixed. If not make sure to let me know

**Comment by GijsBakker** [comment]
A Results folder has been added, so this issue should be fixed. If not make sure to let me know
